# Generated by Django 4.0.5 on 2023-09-17 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0010_remove_collectioninstallment_collection_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Collection',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date')),
                        ('modification', models.DateTimeField(auto_now=True, verbose_name='Modification Date')),
                        ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Collector')),
                        ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer', verbose_name='Customer')),
                    ],
                ),
            ],
            # Table already exists. See app/migrations/0010_remove_collectioninstallment_collection_and_more.py
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='CollectionInstallment',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('amount', models.FloatField(verbose_name='Amount')),
                        ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.collection', verbose_name='Collection')),
                        ('sale_installment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.saleinstallment', verbose_name='Sale Installment')),
                    ],
                ),
            ],
            # Table already exists. See app/migrations/0010_remove_collectioninstallment_collection_and_more.py
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddConstraint(
                    model_name='collectioninstallment',
                    constraint=models.UniqueConstraint(fields=('sale_installment', 'collection'), name='unique_collection'),
                ),
            ],
            # Constraint already exists.
            database_operations=[],
        ),
    ]
