# Generated by Django 4.0.5 on 2023-10-13 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_collection_delivered'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(db_index=True, verbose_name='Date')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.collection', verbose_name='Collection')),
            ],
        ),
    ]
