# Generated by Django 4.0.5 on 2024-04-24 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_collectiondelivery_collector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='delivered',
            field=models.BooleanField(default=False, verbose_name='Collection Delivered'),
        ),
    ]
