# Generated by Django 4.0.5 on 2024-04-26 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_alter_collection_delivered'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='collectiondelivery',
            constraint=models.UniqueConstraint(fields=('collection', 'collector'), name='unique_collection_delivery'),
        ),
    ]
