# Generated by Django 4.0.5 on 2022-10-14 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_product_remove_sale_product_saleproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Amount')),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='collection',
            name='unique_collection',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='sale_installment',
        ),
        migrations.AddField(
            model_name='collectioninstallment',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.collection'),
        ),
        migrations.AddField(
            model_name='collectioninstallment',
            name='sale_installment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.saleinstallment'),
        ),
        migrations.AddConstraint(
            model_name='collectioninstallment',
            constraint=models.UniqueConstraint(fields=('sale_installment', 'collection'), name='unique_collection'),
        ),
    ]
