# Generated by Django 4.0.5 on 2022-10-16 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_collectioninstallment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.customer'),
            preserve_default=False,
        ),
    ]
