# Generated by Django 4.0.5 on 2022-10-31 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_collection_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='collector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Collector'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='collectioninstallment',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.collection', verbose_name='Collection'),
        ),
        migrations.AlterField(
            model_name='collectioninstallment',
            name='sale_installment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.saleinstallment', verbose_name='Sale Installment'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='collector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Collector'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='saleinstallment',
            name='installment',
            field=models.IntegerField(db_index=True, verbose_name='Installment'),
        ),
        migrations.AlterField(
            model_name='saleinstallment',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sale', verbose_name='Sale'),
        ),
        migrations.AlterField(
            model_name='saleinstallment',
            name='status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('PENDING', 'Pending'), ('PARTIAL', 'Partially Paid')], db_index=True, default='PENDING', max_length=50, verbose_name='Payment Status'),
        ),
        migrations.AlterField(
            model_name='saleproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='saleproduct',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sale', verbose_name='Sale'),
        ),
    ]
