# Generated by Django 4.0.5 on 2023-09-17 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_sale_collector'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='collectioninstallment',
                    name='collection',
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='collectioninstallment',
                    name='sale_installment',
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Collection',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='Collection',
                    table='collection_collection',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='CollectionInstallment',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='CollectionInstallment',
                    table='collection_collectioninstallment',
                ),
            ],
        ),
    ]
