# Generated by Django 4.0.5 on 2023-09-17 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_collectioninstallment_collection_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='CollectorSyncLog',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='CollectorSyncLog',
                    table='collection_collectorsynclog',
                ),
            ],
        )
    ]
