# Generated by Django 4.0.5 on 2023-12-19 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_sale_uncollectible'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='remarks',
            field=models.TextField(default='', verbose_name='Remarks'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('brand', 'sku'), name='unique_product'),
        ),
    ]
