# Generated by Django 4.0.5 on 2024-04-24 03:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_sale_remarks_product_unique_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sale_date',
            field=models.DateTimeField(db_index=True, default=datetime.date(2024, 4, 24), verbose_name='Sale Date'),
        ),
    ]
