# Generated by Django 4.0.5 on 2024-04-24 16:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_sale_sale_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 4, 24, 16, 47, 27, 377935, tzinfo=utc), verbose_name='Sale Date'),
        ),
    ]
