# Generated by Django 4.0.5 on 2024-06-13 02:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_sale_sale_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(choices=[('ARR', 'Arrecifes'), ('SAR', 'Capitan Sarmiento'), ('DUG', 'Duggan'), ('LUI', 'La Luisa'), ('SAL', 'Salto'), ('VLI', 'Villa Lía')], max_length=50, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='Sale Date'),
        ),
    ]
